services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    image: nikitauzakov/docker-project-74
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
